Lineage 18.1 update
whatawurst/android_device_sony_yoshino-common pull request #49
Opened 2021-06-08 23:38 UTC by linckandrea

2021-06-09 06:26 UTC, linckandrea commented
hold

2021-06-09 06:32 UTC, Flamefire requested changes

2021-06-09 06:32 UTC, Flamefire commented on BoardConfigPlatform.mk
> +DEFAULT_APNS_FILE := $(PLATFORM_PATH)/config/telephony/apns-conf.xml
Please remove this until LOS fixed their script. See https://github.com/whatawurst/android_device_sony_yoshino-common/issues/46#issuecomment-857421284 for details

2021-07-18 04:00 UTC, derfelot commented
Any updates? If not, I will pick the powerhint commit to an update I want to do later and leave the APN stuff now.

2021-07-19 07:01 UTC, Flamefire commented
I'd remove the 2nd commit and keep the other 2. Tested on my phone with 17.1 and working fine so far.

2021-09-14 21:13 UTC, derfelot commented
I'll close this and pick the two working ones.

2021-09-14 21:13 UTC, closed without merging